name: tcp-server-client-tool
base: core18
version: '1.0'
summary: Easily install to test TCP connections.
description: |
  This software can be used for TCP messaging test tool. Server and Client mode can not be run at the same time. You should run this modes from different machines.

grade: stable
confinement: strict

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
