name: easy-tcp-server-client # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Easily install to test TCP connections.
description: |
  This software can be used for TCP messaging test tool. Server and Client mode can not be run at the same time. You should run this modes from different machines.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: icon.png

parts:
  easy-tcp-server-client:
    source: .
    plugin: qmake
    build-packages:
    - qtdeclarative5-dev
    - qtquickcontrols2-5-dev
    - qttools5-dev
    - libjsoncpp1
    - qmlscene
    - libqt5quick5
    - libqt5quickwidgets5
    - libqt5quickcontrols2-5
    - libqt5quicktemplates2-5
    - qtquickcontrols2-5-examples
    - qtdeclarative5-window-plugin
    - qtdeclarative5-qtquick2-plugin
    - zlib1g-dev
    stage-packages:
    - libjsoncpp1
    - libqt5qml5
    - libqt5quick5
    - libqt5quickcontrols2-5
    - libqt5concurrent5
    - libqt5core5a
    - libqt5gui5
    - qmlscene
    - qml-module-qtquick-controls
    - qml-module-qtquick-controls2
    - qml-module-qtquick-templates2
    - qml-module-qt-labs-platform
    - qml-module-qtquick2
    - qml-module-qtqml-models2
    - qml-module-qt-labs-folderlistmodel
    - qml-module-qtquick-xmllistmodel
    - qml-module-qtwebchannel
    - qml-module-qtwebengine
    - qml-module-qtquick-dialogs
    - qml-module-qtquick-extras
    - qml-module-qtquick-layouts
    - qml-module-qtquick-localstorage
    - qml-module-qtquick-particles2
    - qml-module-qtquick-privatewidgets
    - qml-module-qtquick-scene2d
    - qml-module-qtquick-scene3d
    - qml-module-qtquick-virtualkeyboard
    - qml-module-qtquick-window2
apps:
  easy-tcp-server-client:
    command: opt/tcp_server/bin/tcp_server
    environment:
       DISABLE_WAYLAND: 1
    plugs:
        - home
        - network
        - opengl
        - x11
        - desktop
        - network-manager
        - desktop-legacy
    extensions:
        - kde-neon
